# Generated by Django 3.2.9 on 2022-02-02 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20220122_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image_cover',
            field=models.ImageField(upload_to='movies'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='image_name',
            field=models.ImageField(upload_to='movies'),
        ),
    ]
