# Generated by Django 3.2.9 on 2022-02-02 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_comment_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='comment',
            name='rating',
            field=models.IntegerField(null=True),
        ),
    ]
